name		'juniorsysadmin-dnscache'
version		'0.0.4' 
source		'git://github.com/juniorsysadmin/puppet-dnscache.git'
author		'Ben Spiccia'
summary		'Module for installing dnscache from D. J. Bernstein's djbdns'
description 	'Install and manage dnscache on CentOS/RedHat and Debian systems'
license     	'Apache License, Version 2.0'

dependency  'puppetlabs/apt', '>= 1.4.2'
dependency  'puppetlabs/stdlib', '>= 3.0.0'
dependency  'stahnma/epel', '>= 0.0.6'
